package zmuzik.czechstocks;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import zmuzik.czechstocks.Stock;
import zmuzik.czechstocks.PortfolioItem;
import zmuzik.czechstocks.StockListItem;

import zmuzik.czechstocks.StockDao;
import zmuzik.czechstocks.PortfolioItemDao;
import zmuzik.czechstocks.StockListItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stockDaoConfig;
    private final DaoConfig portfolioItemDaoConfig;
    private final DaoConfig stockListItemDaoConfig;

    private final StockDao stockDao;
    private final PortfolioItemDao portfolioItemDao;
    private final StockListItemDao stockListItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stockDaoConfig = daoConfigMap.get(StockDao.class).clone();
        stockDaoConfig.initIdentityScope(type);

        portfolioItemDaoConfig = daoConfigMap.get(PortfolioItemDao.class).clone();
        portfolioItemDaoConfig.initIdentityScope(type);

        stockListItemDaoConfig = daoConfigMap.get(StockListItemDao.class).clone();
        stockListItemDaoConfig.initIdentityScope(type);

        stockDao = new StockDao(stockDaoConfig, this);
        portfolioItemDao = new PortfolioItemDao(portfolioItemDaoConfig, this);
        stockListItemDao = new StockListItemDao(stockListItemDaoConfig, this);

        registerDao(Stock.class, stockDao);
        registerDao(PortfolioItem.class, portfolioItemDao);
        registerDao(StockListItem.class, stockListItemDao);
    }
    
    public void clear() {
        stockDaoConfig.getIdentityScope().clear();
        portfolioItemDaoConfig.getIdentityScope().clear();
        stockListItemDaoConfig.getIdentityScope().clear();
    }

    public StockDao getStockDao() {
        return stockDao;
    }

    public PortfolioItemDao getPortfolioItemDao() {
        return portfolioItemDao;
    }

    public StockListItemDao getStockListItemDao() {
        return stockListItemDao;
    }

}
