package zmuzik.czechstocks;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STOCK.
 */
public class Stock {

    private Long id;
    /** Not-null value. */
    private String isin;
    /** Not-null value. */
    private String name;
    private double price;
    private double delta;
    /** Not-null value. */
    private java.util.Date stamp;

    public Stock() {
    }

    public Stock(Long id) {
        this.id = id;
    }

    public Stock(Long id, String isin, String name, double price, double delta, java.util.Date stamp) {
        this.id = id;
        this.isin = isin;
        this.name = name;
        this.price = price;
        this.delta = delta;
        this.stamp = stamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIsin() {
        return isin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIsin(String isin) {
        this.isin = isin;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public double getDelta() {
        return delta;
    }

    public void setDelta(double delta) {
        this.delta = delta;
    }

    /** Not-null value. */
    public java.util.Date getStamp() {
        return stamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStamp(java.util.Date stamp) {
        this.stamp = stamp;
    }

}
