package zmuzik.czechstocks.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import zmuzik.czechstocks.dao.CurrentTradingData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CURRENT_TRADING_DATA.
*/
public class CurrentTradingDataDao extends AbstractDao<CurrentTradingData, String> {

    public static final String TABLENAME = "CURRENT_TRADING_DATA";

    /**
     * Properties of entity CurrentTradingData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Isin = new Property(0, String.class, "isin", true, "ISIN");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Price = new Property(2, double.class, "price", false, "PRICE");
        public final static Property Delta = new Property(3, double.class, "delta", false, "DELTA");
        public final static Property Stamp = new Property(4, java.util.Date.class, "stamp", false, "STAMP");
    };


    public CurrentTradingDataDao(DaoConfig config) {
        super(config);
    }
    
    public CurrentTradingDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CURRENT_TRADING_DATA' (" + //
                "'ISIN' TEXT PRIMARY KEY NOT NULL ," + // 0: isin
                "'NAME' TEXT NOT NULL ," + // 1: name
                "'PRICE' REAL NOT NULL ," + // 2: price
                "'DELTA' REAL NOT NULL ," + // 3: delta
                "'STAMP' INTEGER NOT NULL );"); // 4: stamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CURRENT_TRADING_DATA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CurrentTradingData entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getIsin());
        stmt.bindString(2, entity.getName());
        stmt.bindDouble(3, entity.getPrice());
        stmt.bindDouble(4, entity.getDelta());
        stmt.bindLong(5, entity.getStamp().getTime());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CurrentTradingData readEntity(Cursor cursor, int offset) {
        CurrentTradingData entity = new CurrentTradingData( //
            cursor.getString(offset + 0), // isin
            cursor.getString(offset + 1), // name
            cursor.getDouble(offset + 2), // price
            cursor.getDouble(offset + 3), // delta
            new java.util.Date(cursor.getLong(offset + 4)) // stamp
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CurrentTradingData entity, int offset) {
        entity.setIsin(cursor.getString(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setPrice(cursor.getDouble(offset + 2));
        entity.setDelta(cursor.getDouble(offset + 3));
        entity.setStamp(new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(CurrentTradingData entity, long rowId) {
        return entity.getIsin();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(CurrentTradingData entity) {
        if(entity != null) {
            return entity.getIsin();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
