package zmuzik.czechstocks.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CURRENT_QUOTE.
 */
public class CurrentQuote {

    /** Not-null value. */
    private String isin;
    /** Not-null value. */
    private String name;
    private double price;
    private double delta;
    /** Not-null value. */
    private String stamp;

    public CurrentQuote() {
    }

    public CurrentQuote(String isin) {
        this.isin = isin;
    }

    public CurrentQuote(String isin, String name, double price, double delta, String stamp) {
        this.isin = isin;
        this.name = name;
        this.price = price;
        this.delta = delta;
        this.stamp = stamp;
    }

    /** Not-null value. */
    public String getIsin() {
        return isin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIsin(String isin) {
        this.isin = isin;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public double getDelta() {
        return delta;
    }

    public void setDelta(double delta) {
        this.delta = delta;
    }

    /** Not-null value. */
    public String getStamp() {
        return stamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStamp(String stamp) {
        this.stamp = stamp;
    }

}
