package zmuzik.czechstocks.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import zmuzik.czechstocks.dao.CurrentQuote;
import zmuzik.czechstocks.dao.Dividend;
import zmuzik.czechstocks.dao.StockDetail;
import zmuzik.czechstocks.dao.TodaysQuote;
import zmuzik.czechstocks.dao.HistoricalQuote;
import zmuzik.czechstocks.dao.Stock;
import zmuzik.czechstocks.dao.PortfolioItem;

import zmuzik.czechstocks.dao.CurrentQuoteDao;
import zmuzik.czechstocks.dao.DividendDao;
import zmuzik.czechstocks.dao.StockDetailDao;
import zmuzik.czechstocks.dao.TodaysQuoteDao;
import zmuzik.czechstocks.dao.HistoricalQuoteDao;
import zmuzik.czechstocks.dao.StockDao;
import zmuzik.czechstocks.dao.PortfolioItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig currentQuoteDaoConfig;
    private final DaoConfig dividendDaoConfig;
    private final DaoConfig stockDetailDaoConfig;
    private final DaoConfig todaysQuoteDaoConfig;
    private final DaoConfig historicalQuoteDaoConfig;
    private final DaoConfig stockDaoConfig;
    private final DaoConfig portfolioItemDaoConfig;

    private final CurrentQuoteDao currentQuoteDao;
    private final DividendDao dividendDao;
    private final StockDetailDao stockDetailDao;
    private final TodaysQuoteDao todaysQuoteDao;
    private final HistoricalQuoteDao historicalQuoteDao;
    private final StockDao stockDao;
    private final PortfolioItemDao portfolioItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        currentQuoteDaoConfig = daoConfigMap.get(CurrentQuoteDao.class).clone();
        currentQuoteDaoConfig.initIdentityScope(type);

        dividendDaoConfig = daoConfigMap.get(DividendDao.class).clone();
        dividendDaoConfig.initIdentityScope(type);

        stockDetailDaoConfig = daoConfigMap.get(StockDetailDao.class).clone();
        stockDetailDaoConfig.initIdentityScope(type);

        todaysQuoteDaoConfig = daoConfigMap.get(TodaysQuoteDao.class).clone();
        todaysQuoteDaoConfig.initIdentityScope(type);

        historicalQuoteDaoConfig = daoConfigMap.get(HistoricalQuoteDao.class).clone();
        historicalQuoteDaoConfig.initIdentityScope(type);

        stockDaoConfig = daoConfigMap.get(StockDao.class).clone();
        stockDaoConfig.initIdentityScope(type);

        portfolioItemDaoConfig = daoConfigMap.get(PortfolioItemDao.class).clone();
        portfolioItemDaoConfig.initIdentityScope(type);

        currentQuoteDao = new CurrentQuoteDao(currentQuoteDaoConfig, this);
        dividendDao = new DividendDao(dividendDaoConfig, this);
        stockDetailDao = new StockDetailDao(stockDetailDaoConfig, this);
        todaysQuoteDao = new TodaysQuoteDao(todaysQuoteDaoConfig, this);
        historicalQuoteDao = new HistoricalQuoteDao(historicalQuoteDaoConfig, this);
        stockDao = new StockDao(stockDaoConfig, this);
        portfolioItemDao = new PortfolioItemDao(portfolioItemDaoConfig, this);

        registerDao(CurrentQuote.class, currentQuoteDao);
        registerDao(Dividend.class, dividendDao);
        registerDao(StockDetail.class, stockDetailDao);
        registerDao(TodaysQuote.class, todaysQuoteDao);
        registerDao(HistoricalQuote.class, historicalQuoteDao);
        registerDao(Stock.class, stockDao);
        registerDao(PortfolioItem.class, portfolioItemDao);
    }
    
    public void clear() {
        currentQuoteDaoConfig.getIdentityScope().clear();
        dividendDaoConfig.getIdentityScope().clear();
        stockDetailDaoConfig.getIdentityScope().clear();
        todaysQuoteDaoConfig.getIdentityScope().clear();
        historicalQuoteDaoConfig.getIdentityScope().clear();
        stockDaoConfig.getIdentityScope().clear();
        portfolioItemDaoConfig.getIdentityScope().clear();
    }

    public CurrentQuoteDao getCurrentQuoteDao() {
        return currentQuoteDao;
    }

    public DividendDao getDividendDao() {
        return dividendDao;
    }

    public StockDetailDao getStockDetailDao() {
        return stockDetailDao;
    }

    public TodaysQuoteDao getTodaysQuoteDao() {
        return todaysQuoteDao;
    }

    public HistoricalQuoteDao getHistoricalQuoteDao() {
        return historicalQuoteDao;
    }

    public StockDao getStockDao() {
        return stockDao;
    }

    public PortfolioItemDao getPortfolioItemDao() {
        return portfolioItemDao;
    }

}
