package zmuzik.czechstocks.dao;

import zmuzik.czechstocks.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIVIDEND.
 */
public class Dividend {

    private Long id;
    /** Not-null value. */
    private String isin;
    private double amount;
    /** Not-null value. */
    private String currency;
    /** Not-null value. */
    private java.util.Date exDate;
    /** Not-null value. */
    private java.util.Date paymentDate;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient DividendDao myDao;

    private Stock stock;
    private String stock__resolvedKey;


    public Dividend() {
    }

    public Dividend(Long id) {
        this.id = id;
    }

    public Dividend(Long id, String isin, double amount, String currency, java.util.Date exDate, java.util.Date paymentDate) {
        this.id = id;
        this.isin = isin;
        this.amount = amount;
        this.currency = currency;
        this.exDate = exDate;
        this.paymentDate = paymentDate;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDividendDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIsin() {
        return isin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIsin(String isin) {
        this.isin = isin;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    /** Not-null value. */
    public String getCurrency() {
        return currency;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /** Not-null value. */
    public java.util.Date getExDate() {
        return exDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setExDate(java.util.Date exDate) {
        this.exDate = exDate;
    }

    /** Not-null value. */
    public java.util.Date getPaymentDate() {
        return paymentDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPaymentDate(java.util.Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    /** To-one relationship, resolved on first access. */
    public Stock getStock() {
        String __key = this.isin;
        if (stock__resolvedKey == null || stock__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            StockDao targetDao = daoSession.getStockDao();
            Stock stockNew = targetDao.load(__key);
            synchronized (this) {
                stock = stockNew;
            	stock__resolvedKey = __key;
            }
        }
        return stock;
    }

    public void setStock(Stock stock) {
        if (stock == null) {
            throw new DaoException("To-one property 'isin' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.stock = stock;
            isin = stock.getIsin();
            stock__resolvedKey = isin;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
