package zmuzik.czechstocks.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import zmuzik.czechstocks.dao.Dividend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DIVIDEND.
*/
public class DividendDao extends AbstractDao<Dividend, Long> {

    public static final String TABLENAME = "DIVIDEND";

    /**
     * Properties of entity Dividend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Isin = new Property(1, String.class, "isin", false, "ISIN");
        public final static Property Amount = new Property(2, double.class, "amount", false, "AMOUNT");
        public final static Property Currency = new Property(3, String.class, "currency", false, "CURRENCY");
        public final static Property ExDate = new Property(4, java.util.Date.class, "exDate", false, "EX_DATE");
        public final static Property PaymentDate = new Property(5, java.util.Date.class, "paymentDate", false, "PAYMENT_DATE");
    };

    private Query<Dividend> stock_DividendListQuery;

    public DividendDao(DaoConfig config) {
        super(config);
    }
    
    public DividendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DIVIDEND' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ISIN' TEXT NOT NULL ," + // 1: isin
                "'AMOUNT' REAL NOT NULL ," + // 2: amount
                "'CURRENCY' TEXT NOT NULL ," + // 3: currency
                "'EX_DATE' INTEGER," + // 4: exDate
                "'PAYMENT_DATE' INTEGER);"); // 5: paymentDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DIVIDEND'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Dividend entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getIsin());
        stmt.bindDouble(3, entity.getAmount());
        stmt.bindString(4, entity.getCurrency());
 
        java.util.Date exDate = entity.getExDate();
        if (exDate != null) {
            stmt.bindLong(5, exDate.getTime());
        }
 
        java.util.Date paymentDate = entity.getPaymentDate();
        if (paymentDate != null) {
            stmt.bindLong(6, paymentDate.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Dividend readEntity(Cursor cursor, int offset) {
        Dividend entity = new Dividend( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // isin
            cursor.getDouble(offset + 2), // amount
            cursor.getString(offset + 3), // currency
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // exDate
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)) // paymentDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Dividend entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsin(cursor.getString(offset + 1));
        entity.setAmount(cursor.getDouble(offset + 2));
        entity.setCurrency(cursor.getString(offset + 3));
        entity.setExDate(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setPaymentDate(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Dividend entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Dividend entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dividendList" to-many relationship of Stock. */
    public List<Dividend> _queryStock_DividendList(String isin) {
        synchronized (this) {
            if (stock_DividendListQuery == null) {
                QueryBuilder<Dividend> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Isin.eq(null));
                stock_DividendListQuery = queryBuilder.build();
            }
        }
        Query<Dividend> query = stock_DividendListQuery.forCurrentThread();
        query.setParameter(0, isin);
        return query.list();
    }

}
