package zmuzik.czechstocks.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import zmuzik.czechstocks.dao.Dividend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DIVIDEND.
*/
public class DividendDao extends AbstractDao<Dividend, Long> {

    public static final String TABLENAME = "DIVIDEND";

    /**
     * Properties of entity Dividend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Isin = new Property(1, String.class, "isin", false, "ISIN");
        public final static Property Amount = new Property(2, double.class, "amount", false, "AMOUNT");
        public final static Property Currency = new Property(3, String.class, "currency", false, "CURRENCY");
        public final static Property ExDate = new Property(4, java.util.Date.class, "exDate", false, "EX_DATE");
        public final static Property PaymentDate = new Property(5, java.util.Date.class, "paymentDate", false, "PAYMENT_DATE");
    };

    private DaoSession daoSession;


    public DividendDao(DaoConfig config) {
        super(config);
    }
    
    public DividendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DIVIDEND' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ISIN' TEXT NOT NULL ," + // 1: isin
                "'AMOUNT' REAL NOT NULL ," + // 2: amount
                "'CURRENCY' TEXT NOT NULL ," + // 3: currency
                "'EX_DATE' INTEGER NOT NULL ," + // 4: exDate
                "'PAYMENT_DATE' INTEGER NOT NULL );"); // 5: paymentDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DIVIDEND'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Dividend entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getIsin());
        stmt.bindDouble(3, entity.getAmount());
        stmt.bindString(4, entity.getCurrency());
        stmt.bindLong(5, entity.getExDate().getTime());
        stmt.bindLong(6, entity.getPaymentDate().getTime());
    }

    @Override
    protected void attachEntity(Dividend entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Dividend readEntity(Cursor cursor, int offset) {
        Dividend entity = new Dividend( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // isin
            cursor.getDouble(offset + 2), // amount
            cursor.getString(offset + 3), // currency
            new java.util.Date(cursor.getLong(offset + 4)), // exDate
            new java.util.Date(cursor.getLong(offset + 5)) // paymentDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Dividend entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsin(cursor.getString(offset + 1));
        entity.setAmount(cursor.getDouble(offset + 2));
        entity.setCurrency(cursor.getString(offset + 3));
        entity.setExDate(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setPaymentDate(new java.util.Date(cursor.getLong(offset + 5)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Dividend entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Dividend entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getStockDao().getAllColumns());
            builder.append(" FROM DIVIDEND T");
            builder.append(" LEFT JOIN STOCK T0 ON T.'ISIN'=T0.'ISIN'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Dividend loadCurrentDeep(Cursor cursor, boolean lock) {
        Dividend entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Stock stock = loadCurrentOther(daoSession.getStockDao(), cursor, offset);
         if(stock != null) {
            entity.setStock(stock);
        }

        return entity;    
    }

    public Dividend loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Dividend> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Dividend> list = new ArrayList<Dividend>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Dividend> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Dividend> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
