package zmuzik.czechstocks.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIVIDEND.
 */
public class Dividend {

    private Long id;
    /** Not-null value. */
    private String isin;
    private double amount;
    /** Not-null value. */
    private String currency;
    private Long exDate;
    private Long paymentDate;

    public Dividend() {
    }

    public Dividend(Long id) {
        this.id = id;
    }

    public Dividend(Long id, String isin, double amount, String currency, Long exDate, Long paymentDate) {
        this.id = id;
        this.isin = isin;
        this.amount = amount;
        this.currency = currency;
        this.exDate = exDate;
        this.paymentDate = paymentDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIsin() {
        return isin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIsin(String isin) {
        this.isin = isin;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    /** Not-null value. */
    public String getCurrency() {
        return currency;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Long getExDate() {
        return exDate;
    }

    public void setExDate(Long exDate) {
        this.exDate = exDate;
    }

    public Long getPaymentDate() {
        return paymentDate;
    }

    public void setPaymentDate(Long paymentDate) {
        this.paymentDate = paymentDate;
    }

}
