package zmuzik.czechstocks.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import zmuzik.czechstocks.dao.Stock;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STOCK.
*/
public class StockDao extends AbstractDao<Stock, String> {

    public static final String TABLENAME = "STOCK";

    /**
     * Properties of entity Stock.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Isin = new Property(0, String.class, "isin", true, "ISIN");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property ShowInQuotesList = new Property(2, boolean.class, "showInQuotesList", false, "SHOW_IN_QUOTES_LIST");
    };

    private DaoSession daoSession;


    public StockDao(DaoConfig config) {
        super(config);
    }
    
    public StockDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'STOCK' (" + //
                "'ISIN' TEXT PRIMARY KEY NOT NULL ," + // 0: isin
                "'NAME' TEXT NOT NULL ," + // 1: name
                "'SHOW_IN_QUOTES_LIST' INTEGER NOT NULL );"); // 2: showInQuotesList
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STOCK'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Stock entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getIsin());
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getShowInQuotesList() ? 1l: 0l);
    }

    @Override
    protected void attachEntity(Stock entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Stock readEntity(Cursor cursor, int offset) {
        Stock entity = new Stock( //
            cursor.getString(offset + 0), // isin
            cursor.getString(offset + 1), // name
            cursor.getShort(offset + 2) != 0 // showInQuotesList
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Stock entity, int offset) {
        entity.setIsin(cursor.getString(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setShowInQuotesList(cursor.getShort(offset + 2) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Stock entity, long rowId) {
        return entity.getIsin();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Stock entity) {
        if(entity != null) {
            return entity.getIsin();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCurrentQuoteDao().getAllColumns());
            builder.append(" FROM STOCK T");
            builder.append(" LEFT JOIN CURRENT_QUOTE T0 ON T.'ISIN'=T0.'ISIN'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Stock loadCurrentDeep(Cursor cursor, boolean lock) {
        Stock entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CurrentQuote currentQuote = loadCurrentOther(daoSession.getCurrentQuoteDao(), cursor, offset);
         if(currentQuote != null) {
            entity.setCurrentQuote(currentQuote);
        }

        return entity;    
    }

    public Stock loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Stock> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Stock> list = new ArrayList<Stock>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Stock> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Stock> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
