package zmuzik.czechstocks.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import zmuzik.czechstocks.dao.StockInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STOCK_INFO.
*/
public class StockInfoDao extends AbstractDao<StockInfo, Long> {

    public static final String TABLENAME = "STOCK_INFO";

    /**
     * Properties of entity StockInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Isin = new Property(1, String.class, "isin", false, "ISIN");
        public final static Property Indicator = new Property(2, String.class, "indicator", false, "INDICATOR");
        public final static Property Value = new Property(3, String.class, "value", false, "VALUE");
    };

    private Query<StockInfo> stock_StockInfoListQuery;

    public StockInfoDao(DaoConfig config) {
        super(config);
    }
    
    public StockInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'STOCK_INFO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ISIN' TEXT NOT NULL ," + // 1: isin
                "'INDICATOR' TEXT NOT NULL ," + // 2: indicator
                "'VALUE' TEXT NOT NULL );"); // 3: value
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STOCK_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, StockInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getIsin());
        stmt.bindString(3, entity.getIndicator());
        stmt.bindString(4, entity.getValue());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public StockInfo readEntity(Cursor cursor, int offset) {
        StockInfo entity = new StockInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // isin
            cursor.getString(offset + 2), // indicator
            cursor.getString(offset + 3) // value
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, StockInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsin(cursor.getString(offset + 1));
        entity.setIndicator(cursor.getString(offset + 2));
        entity.setValue(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(StockInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(StockInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "stockInfoList" to-many relationship of Stock. */
    public List<StockInfo> _queryStock_StockInfoList(String isin) {
        synchronized (this) {
            if (stock_StockInfoListQuery == null) {
                QueryBuilder<StockInfo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Isin.eq(null));
                stock_StockInfoListQuery = queryBuilder.build();
            }
        }
        Query<StockInfo> query = stock_StockInfoListQuery.forCurrentThread();
        query.setParameter(0, isin);
        return query.list();
    }

}
