package zmuzik.czechstocks.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STOCK_DETAIL.
 */
public class StockDetail {

    private Long id;
    /** Not-null value. */
    private String isin;
    /** Not-null value. */
    private String indicator;
    /** Not-null value. */
    private String value;

    public StockDetail() {
    }

    public StockDetail(Long id) {
        this.id = id;
    }

    public StockDetail(Long id, String isin, String indicator, String value) {
        this.id = id;
        this.isin = isin;
        this.indicator = indicator;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIsin() {
        return isin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIsin(String isin) {
        this.isin = isin;
    }

    /** Not-null value. */
    public String getIndicator() {
        return indicator;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIndicator(String indicator) {
        this.indicator = indicator;
    }

    /** Not-null value. */
    public String getValue() {
        return value;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setValue(String value) {
        this.value = value;
    }

}
